.eslintrc.json
package.json
src/bot/index.ts
src/server/storage.ts
yarn.lock

That's the best practice, accessing the raw event directly [is not advised](https://matrix-org.github.io/matrix-js-sdk/9.1.0/module-models_event.MatrixEvent.html).

Bump deps and use getter instead of raw event

---

src/bot/index.ts

closes #25 
The bot only talks when there's a !
It tells if it doesn't understand the command.

Make the bot less talkative

---

kubernetes/faucetbot/templates/deployment.yaml

this might do the trick already. just added a timestamp annotaion to the deployment

add timestamp annotation

---

src/server/ErrorCounter.ts
src/server/actions.ts
src/server/index.ts

closes #17 
`localhost:5555/metrics` will return
```
errors_total 2
```

Add prometheus /metrics endpoint with the total amount of errors

---

kubernetes/faucetbot/westend-values.yaml

this pr will replace the to old faucet https://gitlab.parity.io/chains/westend-faucet/

setup for production

---

.gitlab-ci.yml
README.md

Minor changes to the README and CI (only build on **main** branch).

Fv last bits

---

package.json
yarn.lock

- tested on Westend without issue, on Canvas the node can't be connected to (it has a TLS handshake error that does not seem related to this, since polkadot apps can't connect to it either).
gettting this when launching the bot, need to check
```
[2021-01-12T19:13:12.902] [ERROR] default - M_UNKNOWN: No known servers
at parseErrorResponse (/home/thib/github/paritytech/substrate-matrix-faucet/node_modules/matrix-js-sdk/lib/http-api.js:826:13)
at /home/thib/github/paritytech/substrate-matrix-faucet/node_modules/matrix-js-sdk/lib/http-api.js:781:17
at Request._callback (/home/thib/github/paritytech/substrate-matrix-faucet/node_modules/matrix-js-sdk/lib/http-api.js:715:9)
at Request.self.callback (/home/thib/github/paritytech/substrate-matrix-faucet/node_modules/request/request.js:185:22)
at …
```

Bump all deps

---

package.json

https://github.com/paritytech/substrate-matrix-faucet/issues/48

bump js version to 3.11.1

---

package.json
yarn.lock

Bump dependency versions

---

package.json
yarn.lock

bump deps?

---

src/bot/index.ts

FIx https://github.com/paritytech/substrate-matrix-faucet/issues/38

Trim whitespaces in the address

---

src/server/index.ts

Add the `web3.foundation` domain to the privileged accounts.
fix #72

Add web3.foundation to the privileged domains

---

README.md

Minor fix to force redeploy

---

README.md
deployment.template.yaml
kubernetes/faucetbot/templates/deployment.yaml
src/server/actions.ts
src/server/index.ts
src/server/rpc.ts

Fix https://github.com/paritytech/substrate-matrix-faucet/issues/93

Add readiness probe

---

kubernetes/faucetbot/templates/deployment.yaml

Change deployment template

---

src/bot/index.ts

Fix logic of custom dripping amount (allow web3f)

---

.gitlab-ci.yml

Make explicit deployments, rather than merging to main

---

.gitlab-ci.yml
CODEOWNERS

Removed unused components from `check-*` jobs.
Closes https://github.com/paritytech/ci_cd/issues/389

[CI] fix checks jobs

---

.gitlab-ci.yml

Also remove the dry-run part as it is useless if you actually upgrade just after.

Automate rollbacks on failed upgrades

---

package.json
yarn.lock

Fix: https://github.com/paritytech/opstooling/issues/124

fix dependencies

---

.eslintrc.json
.gitignore
package.json
src/server/services/ActionStorage.spec.ts
src/server/services/ActionStorage.ts
src/utils.spec.ts
yarn.lock

Remove NeDB & unsecure dependencies, replace with sqlite3

---

docker/docker-compose.westend.yml
kubernetes/rococo-values.yaml
kubernetes/westend-values.yaml

Reverts paritytech/substrate-matrix-faucet#176

Revert "Trying to fix prod deployment"

---

.gitlab-ci.yml

Current buildah image is broken. Using the previous one
cc https://github.com/paritytech/ci_cd/issues/671

[ci] fix buildah image

---

docker/docker-compose.rococo.yml
docker/docker-compose.versi.yml
src/utils.spec.ts
src/utils.ts

This PR grants Parity user coming from the new Matrix server URL privileged access on the faucets
https://github.com/paritytech/substrate-matrix-faucet/pull/181 🙏

Switch to new parity matrix server URL

---

src/server/routes/actions.ts
src/types.ts

This change should have no functional changes in behaviour - just a refactoring in preparation for adding a new, similar endpoint for non-bots.

Refactor: Extract the drip request handler

---

src/server/routes/actions.ts

Closes https://github.com/paritytech/substrate-matrix-faucet/issues/190
I have plans to introduce some E2E smoke tests to catch this kind of stuff.

Properly bind response sending function

---

e2e/bootstrap.sh
e2e/docker-compose.infrastructure.yml
e2e/matrix_data/homeserver.yaml
package.json
src/dripper/polkadot/PolkadotActions.ts
src/faucet.e2e.ts
src/utils.ts
yarn.lock

- Progresses https://github.com/paritytech/substrate-matrix-faucet/issues/224
- Changed E2E matrix server name to `parity.io` so that in E2E tests we can drip multiple times by being privileged.

Change teleport mechanism from V1 to V2

---

.gitlab-ci.yml

Required for fixing deployment

Fix versi faucet argocd app name

---

.github/workflows/deploy-site.yml
client/.eslintrc.cjs
client/.prettierrc
client/README.md
client/playwright.config.ts
client/postcss.config.cjs
client/src/app.css
client/src/app.d.ts
client/src/app.html
client/src/lib/components/CaptchaV2.svelte
client/src/lib/components/Card.svelte
client/src/lib/components/Form.svelte
client/src/lib/components/SocialTags.svelte
client/src/lib/components/icons/Cross.svelte
client/src/lib/components/icons/Tick.svelte
client/src/lib/utils/faucetRequest.ts
client/src/routes/+layout.svelte
client/src/routes/+page.svelte
client/svelte.config.js
client/tailwind.config.cjs
client/tests/test.ts
client/vite.config.ts

Added linting to the project (it actually already had it, I just didn't use it as it would change to many files).
Ran `yarn run format` which runs the included eslint and prettier (which has pluggins formated for svelte language so I don't know if we can actually use `opstooling-js-style` for this case)
Added CI step for running this new step.

client: added linting & test

---

client/src/app.html

Based on [this notion article](https://www.notion.so/paritytechnologies/Simple-Analytics-Installation-80f00904ac12490983d76a132236b7d3) this are the correct analytics.
And there is a project that handles github pages, which will be used.

added analytics

---

.github/workflows/github-issue-sync.yml
Dockerfile.README.md
README.md
client/Dockerfile.README.md
client/README.md

Required by #237 
Renamed every readme or file that refered to the old repository name in exchange for the new repository name.

renamed all references of the old repo

---

.github/workflows/tag-client-pr.yml
client/src/lib/components/Form.svelte
client/src/lib/components/ParachainModal.svelte
client/src/lib/utils/faucetRequest.ts
client/src/lib/utils/networkData.ts
client/src/routes/+layout.ts
client/src/routes/+page.svelte
client/tests/test.ts

Added a modal where the user can select a default chain, a predefined chain or add their own.
This closes #247

added parachain selection modal

---

client/package.json
client/yarn.lock
e2e/zombienet.native.toml
src/dripper/DripRequestHandler.ts
src/faucet.e2e.ts

Simple check to verify that the parachain id is a number and it is between 1000 and 9999.
Closes #213

added parachain id validation on server

---

.github/ISSUE_TEMPLATE/faucet.yml

As matrix and web users could have problems with the faucet in the future, I recommend that we have a template to facilitate them when writing issues.

Created issue template for faucet problems

---

.github/workflows/E2E.yml
README.md
e2e/README.md

Closes https://github.com/paritytech/polkadot-testnet-faucet/issues/258

Add Readme for the E2E tests

---

.gitlab-ci.yml
CODEOWNERS
Dockerfile

PR updates buildah command and version. More info can be found in https://github.com/paritytech/ci_cd/issues/779

[ci] Update buildah command and version

---

client/.env
client/src/app.css
client/src/app.html
client/src/lib/components/Footer.svelte
client/src/lib/components/NavBar.svelte
client/src/routes/+page.svelte
client/static/circle.svg

This PR finally closes #266 
It adds the background image with the spheres.
It also fixes a small problems with the navbar and footer so they look better on different screen sizes.

client: background

---

src/dripper/polkadot/PolkadotActions.ts

Changed `await Promise.resolve(x)` to simply `x`.

Remove unnecessary code construct

---

src/bot/index.ts
src/networkData.ts

This time, actually tested locally

Subscan URL fix [2]

---

.github/workflows/deploy-site.yml
.gitlab-ci.yml

* Removing old ink-docs faucet deployment
* Used new merged faucet endpoint for the client

Merging rococo faucets

---

.env.example
env.faucet.config.json
src/bot/index.ts
src/server/routes/healthcheck.ts
src/test/setupE2E.ts
yarn.lock

This seems to be causing re-deployments every time argoCD configuration
updates.

Removed SMF_CONFIG_DEPLOYED_TIME variable

---

Dockerfile
env.faucet.config.json

\+ masking database passsword in logs

Running migrations on the start

---

src/dripper/dripperStorage.ts

It was meant to be 20 hours, not 20 days...

Drip query fix

---

.gitlab-ci.yml

fix: https://github.com/paritytech/devops/issues/2924

Retire Wococo

---

src/networkData.ts

- Add Paseo config: https://forum.polkadot.network/t/the-new-polkadot-community-testnet/4956
- Remove Wococo config as the network is now shut down: https://wiki.polkadot.network/docs/maintain-networks#wococo-test-network-inactive

Update testnets config: add Paseo, remove Wococo

---

client/.env
client/src/app.css
client/src/lib/components/Footer.svelte
client/src/lib/components/Form.svelte
client/src/lib/components/NetworkDropdown.svelte
client/src/lib/components/NetworkInput.svelte
client/src/lib/utils/networkData.ts
client/src/routes/paseo/+page.svelte
client/tests/faucet.ts
client/tests/paseo.test.ts
client/tests/rococo.test.ts
client/tests/westend.test.ts
src/__mocks__/networkData.ts
src/networkData.ts
src/utils.spec.ts
src/utils.ts

Closes #370 -> add paseo to UI, + whitelist paseo people separately from common pattern of parity and w3f
Closes #365 -> fix UX

add paseo, fix UX, whitelist paseo people separatelly

---

client/src/lib/components/Faucet.svelte
client/src/lib/components/MarkUp.svelte
client/src/lib/utils/index.ts

It generates a JSON object inside the header following the instructions from: https://developers.google.com/search/docs/appearance/structured-data/faqpage
It parses the information of the markdown text to generate this json object.
This resolves #277

Added markup code generation

---

helm/Chart.yaml
helm/templates/secrets.yaml
helm/values-parity-testnet-paseo.yaml
helm/values-parity-testnet-rococo.yaml
helm/values-parity-testnet-trappist.yaml
helm/values-parity-testnet-westend.yaml
helm/values-parity-versi.yaml
helm/values.yaml

Part of https://github.com/paritytech/devops/issues/3323

Move charts to its application repos

---

package.json
yarn.lock

Upgrading PAPI to 0.8.0

---

client/src/lib/components/NetworkDropdown.svelte

Added a z-index to make it appear on top of the next input
Fixes #423

fixed dropdown behind input box

---

client/src/lib/components/Card.svelte
client/src/lib/components/Faucet.svelte
client/src/lib/utils/networkData.ts
client/src/routes/+page.svelte
client/src/routes/rococo/+page.svelte
client/tests/paseo.test.ts
client/tests/rococo.test.ts
client/tests/switch.test.ts

Resolves #424
I also added a new header text as requested by @lovelaced

Set paseo as default network

---

.gitlab-ci.yml

Forgot to add build/publish part

Fix deploying staging on tags

---

package.json
yarn.lock

[This change](https://github.com/polkadot-api/polkadot-api/pull/723)
is aimed to fix faucet crashes.
Related to #438

papi@^1.3.0

---

package.json
yarn.lock

Yet another crash fix + annoying logs fix
https://github.com/polkadot-api/polkadot-api/releases/tag/polkadot-api%401.3.1

polkadot-api@1.3.1

---

client/src/lib/components/NetworkInput.svelte
client/src/lib/utils/stores.ts
package.json
src/bot/index.ts
src/faucet.e2e.ts
src/papi/chains/e2e.ts
src/papi/chains/index.ts
src/papi/chains/paseo.ts
src/papi/chains/versi.ts
src/papi/chains/westend.ts
src/server/routes/actions.spec.ts
src/server/routes/actions.ts
src/utils.ts
yarn.lock

Fixes #459
I'm still thinking on how to properly test ethereum drips, will follow
up on that.

ETH address conversion + storing parachain in URL

---

client/src/lib/utils/networkData.ts
client/tests/paseo.test.ts

Temporary parachain for smart contracts

Added Passet Hub

---

client/src/lib/assets/FAQ.md

Link to the parachains is broken and replaced with correct one.

fix(faq): broken link

---

client/.gitignore
client/package.json
client/src/app.css
client/src/lib/components/Card.svelte
client/src/lib/components/NetworkDropdown.svelte
client/src/lib/utils/networkData.ts
client/src/routes/+page.svelte
client/src/routes/westend/+page.svelte
client/tests/paseo.test.ts
client/tests/switch.test.ts
client/yarn.lock

fixes #480
+ upgraded playwright, which fixed the test running locally

Text updates
