- .gitlab-ci.yml
this change will build new server/bot images with every release and deploy the corresponding images faucet-[server|bot]:dockerTag.
this will: 
a) make sure a fresh container is (re)started with every deployement 
b) helm rollback will work properly in case it's needed.
> deploy image:$dockerTag not :latest

- .gitlab-ci.yml
- kubernetes/faucetbot/westend-values.yaml
deploys an 2nd instance of the faucet hooked up to westen faucet address / westend-rpc node and a test matrix room. this is for testing the deployment und should not interfere with the existing westend-faucet.
> added new environment for westend (testing)

- src/server/ErrorCounter.ts
- src/server/actions.ts
- src/server/index.ts
Example of the prometheus metrics now:
```
errors_total 1
errors_rpc_timeout 1
```
> Log on api reconnect and timeout and new prometheus metric

- .gitlab-ci.yml
use `buildah` instead of `docker` to create docker images.
> gitlab-ci no longer supports docker

- README.md
- kubernetes/faucetbot/values.yaml
- kubernetes/faucetbot/westend-values.yaml
- src/bot/index.ts
- src/server/storage.ts
closes #https://github.com/paritytech/substrate-matrix-faucet/issues/2
If you look at the faucet channel, you'll see that most users actually request twice a drip without a short time frame. If that was too quick, it results in https://github.com/paritytech/substrate-matrix-faucet/issues/2.
Making the UX better, and preventing the error, we now allow only 1 request per day, but get 2x more tokens :money_with_wings:
> Double the drip, but once per day

- src/bot/index.ts
- src/server/actions.ts
closes #5
closes #39
closes https://github.com/paritytech/substrate-matrix-faucet/issues/3
This PR makes the bot work in such a way that it will connect to the WS endpoint right before doing something, and will then disconnect. This should prevent disconnection spam.. and faucet's unavailability :crossed_fingers: 
The api emits info about the WS connection being closed, after each token transfer like:
```
[2021-01-28T19:00:40.102] [INFO] default - Faucet backend listening on port 5555.
[2021-01-28T19:00:40.612] [INFO] default - 🤖 Beep bop - Creating the bot's account
[2021-01-28T19:00:52.700] [INFO] default - 💸 sending tokens
2021-01-28 19:00:56        RPC-CORE: subscribeStorage(keys?: Vec<StorageKey>): StorageChangeSet:: WebSocket is not connected
[2021-01-28T19:01:01.868] [INFO] default …
```
> Connect only when needed

- kubernetes/faucetbot/templates/service.yaml
* added a k8s *Service* on port :5555 to expose the prometheus exporter
* added a k8s *ServiceMonitor* so the enpoint can be picked up automatically
> scrape metrics via "ServiceMonitor"

- kubernetes/faucetbot/templates/service.yaml
fix for:  `spec.endpoints.port in body must be of type string:`
```
matchLabels:
app.kubernetes.io/name: faucetbot
app.kubernetes.io/instance: canvas
endpoints:
- port: 5555
interval: 15s
$ helm upgrade ${CI_ENVIRONMENT_NAME} kubernetes/faucetbot --install --namespace ${KUBE_NAMESPACE} --values kubernetes/faucetbot/${CI_ENVIRONMENT_NAME}-values.yaml --set server.secret.FAUCET_ACCOUNT_MNEMONIC="${FAUCET_ACCOUNT_MNEMONIC}" --set server.image.dockerTag="${DOCKER_TAG}" --set bot.secret.MATRIX_ACCESS_TOKEN="${MATRIX_ACCESS_TOKEN}" --set bot.image.dockerTag="${DOCKER_TAG}"
Error: UPGRADE FAILED: failed to create resource: ServiceMonitor.monitoring.coreos.com "canvas-server-metrics" is invalid: spec.endpoints.port: Invalid value: "integer": spec.endpoints.port in body must be of type string: …
```
> ServiceMonitor endpoint must be type str

- src/server/actions.ts
Fix https://github.com/paritytech/substrate-matrix-faucet/issues/51
See: https://polkadot.js.org/docs/api/cookbook/tx/#how-do-i-take-the-pending-tx-pool-into-account-in-my-nonce
> Query nonce to prevent low priority error

- .dockerignore
- package.json
- src/server/actions.ts
- src/server/index.ts
- src/types.ts
- src/utils.ts
- tsconfig.json
This PR adds new Prometheus metrics:
- balance
- total_requests
- successful_requests
It also does:
- remove all the console.log and switch to using the logger
- log the version at start
- bump the server version
- ⚠️ move previous metrics to the new `faucet_` namespace (see example below) 
The goal was not to rewrite too much code so the following is left for other PRs:
- #80 
- #82 
```
faucet_errors_total 0
faucet_errors_rpc_timeout 0
faucet_balance 8.36929
faucet_total_requests 0
faucet_successful_requests 0
```
fix #67
> Add prometheus metrics (including faucet balance)

- README.md
- src/server/actions.ts
- src/server/index.ts
- src/server/serverEnvVars.ts
- src/types.ts
- src/utils.ts
Fixes #70 
I've defaulted this to `100` but let me know if you prefer another limit
> Threshold limit on the amount the faucet can dispense to an account

- README.md
- package.json
- src/bot/index.ts
- src/server/actions.ts
- src/server/index.ts
- src/server/rpc.ts
- src/types.ts
- src/utils.ts
- yarn.lock
Closes https://github.com/paritytech/substrate-matrix-faucet/issues/119.
This is needed because right now there's a lot of friction for users who just want to play with a parachain on e.g. Rococo. At the moment they need to go through the faucet and teleport the tokens by themselves.
With this PR this syntax will be supported by the bot:
```
!drip 5HmabHMibTGNB18ALDVmUxbDu4k4UseuUEuxLRp4cr6Ntb9t:1002
```
I've tested it locally with `polkadot-launch` and a Rococo + Canvas setup, but can't test it properly with an actual Element room. Is there a way for us to do a test deployment?
> Implement dripping to common good parachains via teleport

- .gitlab-ci.yml
After GitLab mirroring changed pipeline is broken.
This PR fixes paths to Vault secrets in CI.
> Fix paths to vault secrets in CI

- .gitlab-ci.yml
Currently the pipeline for `main` branch doesn't publish the image for staging. The PR fixes this
> [ci] fix deploy staging

- src/server/routes/actions.ts
Just a tiny change that finishes handling the request in the event of an error.
Otherwise, the request hangs forever, as tested locally with `curl`.
> Finish the request handling in the case of an error

- jest.config.js
Otherwise it duplicates the tests by running built js files in `build/`
> Specify jest roots

- .dockerignore
- bot_injected.Dockerfile
- package.json
- server_injected.Dockerfile
Some optimization mechanics for the docker images - very useful when changing the code and rebuilding the images.
1. Move the `apk add` commands to top - so that this layer can be cached between code changes
2. Split the step of `yarn install`, so that the layer with `node_modules` can be cached between code changes
There are a lot of unnecessary stuff in the docker build context:
```bash
./README.md
./server_injected.Dockerfile
./tsconfig.json
./jest.config.js
./env.server.config.json
./.eslintignore
./env.bot.config.json
./.prettierignore
./nodemon.json
./bot_injected.Dockerfile
./.eslintrc.cjs
./.idea
./.idea/workspace.xml
./.idea/modules.xml
./.idea/.gitignore
./.idea/optimize-faucet.iml
./.idea/vcs.xml
./.gitlab-ci.yml
./yarn.lock
./src
./src/faucetConfig.ts
./src/logger.ts …
```
> Optimize docker image (re)builds

- src/server/routes/actions.ts
- src/types.ts
This PR tries to divide the endpoints into two different methods.
It adds a couple of improvements to reduce duplicated code.
It created the following endpoints:
- `faucet/`
- `drip-v2/`
I kept the default drip endpoint to not break the already existing implementation, but if `drip-v2` works, we could replace `drip` with that one.
The `faucet` endpoint only handles the expected values coming from the faucet clients (!ink docs and the web faucet) while the drip endpoint handles the other part of the requests.
This way we remove ifs from the code and can also isolate the endpoints.
It adds a couple of improvements to reduce duplicated code.
```typescript
const addressMiddleware = (
req: Request<unknown, DripResponse, Partial<DripRequestType>>,
res: Response,
next: NextFunction,
): void => { …
```
> Divided endpoints based on faucet or drip bot

- client/src/lib/Form.svelte
Added the field `pattern="\d*"` to the network input which, on phones, brings up the numeric keyboard instead of the regular keyboard.
Just a very small QoL improvement.
> added number pattern to parachain input

- .github/workflows/E2E.yml
- e2e/bootstrap.sh
- e2e/docker-compose.deployment.yml
- e2e/docker-compose.infrastructure.yml
- e2e/zombienet.native.toml
- jest.e2e.config.js
- package.json
- src/faucet.e2e.ts
- Change current way of running polkadot to zombienet, in order to add a parachain
- Properly test asset teleportation
- Change the tests so they no longer assert balance of `0` at the beginning, so they no longer fail when re-run
- Add some missing tests, such as checking balance via web endpoint
- Closes https://github.com/paritytech/substrate-matrix-faucet/issues/231
- Closes https://github.com/paritytech/substrate-matrix-faucet/issues/212
- I've run this on CI multiple times to check flakiness. To me it seems non-flaky enough for this kind of test, but it's not at a 100% success rate.
> E2E: Add a parachain, and test asset teleportation

- client/src/lib/components/CaptchaV2.svelte
This closes #242
There was a race condition where sometimes the script of the captcha component hasn't loaded on time and it was causing a runtime error.
This commit modifies the code so that all the window methods are set first, and then the script tag is imported, this way we know that the required environment for the captcha is correctly set up.
> fixed captcha race condition on load

- client/README.md
- client/src/routes/+page.svelte
This PR updates some copy around the Rococo faucet and removes the mention of ink! docs on the rendered page. It may be useful to link to some more relevant documentation about using Rococo in a future PR once the page gets some design love.
> Update copy for Rococo faucet

- Dockerfile
The E2E docker image was failing because the version couldn't be downloaded.
With this patch, it will download the latest version, which should fix any collision issues.
Fixes #264
> removed git version in Dockerfile

- .github/workflows/deploy-site.yml
- client/src/lib/components/NavBar.svelte
- client/src/lib/utils/networkData.ts
- client/svelte.config.js
- client/vite.config.ts
Fixed errors caused when the base of the project is not `/`.
This changes get into consideration having a different base for the occasion that it is being built in a root directory, or, like in github pages, in a `/polkadot-testnet-faucet` directory.
> Fixed error on different base

- client/src/lib/components/NavBar.svelte
Made the "Questions" button hide in mobile. This is because too many buttons in the UI sometimes overflow the width on the screen.
In my phone which has a small screen I could see the screen overflowing.
With the btn:
Without the btn:
> question btn hidden on mobile

- client/src/lib/components/Faucet.svelte
- client/src/lib/components/Form.svelte
- client/src/lib/components/screens/FrequentlyAskedQuestions.svelte
- client/src/lib/components/screens/Success.svelte
Updated the success screen to use the url from the block explorer instead of a hardcoded one.
This commit closes #293 
Deleted residual code from before the existence of the success and failure screens.
Also, modified margins on mobile so the FAQ section isn't that far away and you don't need to scroll that much.
> Fixed block explorer 🧱 url in success screen

- .github/workflows/E2E.yml
- e2e/README.md
Attempting to reproduce https://github.com/paritytech/polkadot-testnet-faucet/issues/286 (without luck).
> Update the E2E tests to run against Polkadot v0.9.42

- src/dripper/polkadot/PolkadotActions.ts
Related to https://github.com/paritytech/polkadot-testnet-faucet/issues/286
It seems like `teleportAssets` is hitting a barrier but `limitedTeleportAssets` is not - even though we have an unlimited limit.
> Change teleportAssets to limitedTeleportAssets

- src/networkData.ts
Seems that balance cap being 10 times drip amount is an established rule
of thumb, so aligned it for all networks
> 10 WND drip amount for westend, fixed balance cap for other networks

- .github/workflows/deploy-site.yml
- client/.env
- client/.eslintrc.cjs
- client/README.md
- client/playwright.config.ts
- client/src/lib/components/Form.svelte
- client/src/lib/components/screens/Success.svelte
- client/src/lib/utils/networkData.ts
- client/src/routes/+page.svelte
- client/src/routes/trappist/+page.svelte
- client/tests/faucet.ts
- client/tests/rococo.test.ts
- client/tests/trappist.test.ts
- client/tests/westend.test.ts
- package.json
- src/networkData.ts
- yarn.lock
Stopped copying known static urls like PUBLIC_FAUCET_ROCOCO_URL, storing
it in NetworkData now.
Setting PUBLIC_FAUCET_URL to anything non-empty will override all
requests to it.
Trappist doesn't exist on subscan yet, so making it optional.
> Trappist faucet + updates

- .env.example
- src/dripper/polkadot/PolkadotActions.ts
This PR fixes two things:
- For the `.env` that var appears two times
- For networks that have very high decimals that don't fit in a normal int64 the current approach doesn't work as it can't calculate 10 ** decimals. So we have to use BN as well to make that calculation
> Fix drip for networks with high decimals

- src/dripper/polkadot/PolkadotActions.ts
Fix for failed teleport in Rococo faucet bot 
I couldn't find any release notes regarding this change :(
just went to https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-rpc.polkadot.io#/extrinsics and looked up the xcmPallet.limitedTeleportAssets method, where i saw expected types, which helped to migrate
the only difference is that all networks (westend, polkadot, kusama) except Rococo use similar types but without "Staging" prefix
Weird, but okay... if/when any other network also starts using Staging - it'd be easy to fix by adding them to condition.. still wondering how would I learn about this change in front
> Fix teleport xcm types

- package.json
- src/start.ts
- yarn.lock
Fixes #223
+ Adding prom-client dependency, because it was removed from
@eng-automation/js (rightfully so)
> Adding runtimeRestarter

- e2e/README.md
@josepot has reported an error with `@zombienet/cli@1.3.43`, while the
latest version worked
> Updating zombinenet verion in e2e docs

- .github/workflows/deploy-site.yml
This removes the base url, making the website work on the root of the domain.
Also, by doing this change, and having set up the dns, this resolves #348
> removed base url

- .github/workflows/deploy-site.yml
We currently don't have an artifact retention period, so it defaults to 90 days.
While the artifact for the site is not too big, having one build per push and PR can quickly accumulate the amount and make us hit our hard limit.
By adding a limit to the retention day of 5 days we ensure that we get rid of the old artifacts faster than waiting for two whole months.
I also updated all the actions version to latest release
> Updated actions to latest and added retention period

- client/src/lib/components/NetworkDropdown.svelte
As the Frequency Faucet now also supports Frequency Paseo testnet in addition to the Rococo one, the url is being set to a generic one instead of specific for the network.
https://faucet.testnet.frequency.xyz/
> Update Frequency Faucet URL

- .github/workflows/tag-client-pr.yml
It fails when an external contributors make a PR.
This will fix that issue.
> moved tag-client to work in pull_request_target

- .github/workflows/deploy-site.yml
- .github/workflows/test.yml
- .gitlab-ci.yml
> Moved GitLab checks to GitHub's action

- src/dripper/polkadot/PolkadotActions.ts
- yarn.lock
The source of the error was, that I treated the observables the wrong
way.
I expected `submitAndWatch()` to return a chain of events, to which I
could subscribe from a bunch of sources, while it actually led to side
effects being multiplied in the sources.
`shareReplay()` returns a multicast observable that actually behaves the
way I expected it to.
> Fixing "Invalid" error

- src/dripper/polkadot/PolkadotActions.ts
If two transactions use `getNonce()` at the same time, they'll get
basically the same promise instance, which resolves to the same nonce.
With this change, all consecutive `getNonce()` calls will return
different promise instances, with the increment preformed.
> Fixing possible race condition

- src/dripper/polkadot/PolkadotActions.ts
I probably did a bad job at explanning how `shareReplay` works, my apologies.
The thing is that every time that with `shareReplay` every time that its internal refCount goes down to zero, then it unsubscribes from the source.
Therefore, there must be a subscription always open for the observable to be "shared". This is because observables are not eager. What was happening is that every time the old code was performing a `firstValueFrom` that creates a subscription and when the condition is met (and the promise resolves) then it unsubscribes from the observable. Since that was its only subscription, then the refcount goes down to 0 and the observable dies. So, the next `firstValueFrom` creates a brand new subscription.
I realize that people coming from PJS may find Observables difficult to …
> Fixing "Invalid" Error II

- .gitlab-ci.yml
- CODEOWNERS
- Dockerfile
- README.md
- helm/values-parity-testnet-paseo.yaml
- helm/values-parity-testnet-westend.yaml
- package.json
- polkadot-api.json
- src/papi/chains/paseo.ts
- yarn.lock
Closes https://github.com/paritytech/polkadot-testnet-faucet/issues/419
> Change Paseo RPC to wss://sys.dotters.network/paseo

- package.json
- src/bot/index.ts
- yarn.lock
Analogous to how the tip bot works, introduced reactions.
The user will get immediate feedback that the command has been received.
> Introduce reactions

- helm/Chart.yaml
- helm/values.yaml
After recent PAPI upgrade, faucets started to get OOMs due to huge peak
in memory usage during startup.
While the issue is being worked on, adding more memory to survive it.
> Temporary add more memory

- src/papi/client.ts
This should fix `TypeError: Cannot read properties of undefined (reading
'number')` crashes.
See https://github.com/polkadot-api/polkadot-api/issues/710
Related to #438, but isn't the only reason for crashes
> Using fixUnorderedBlocks compat from papi

- src/papi/client.ts
there's a theory that papi-related crashes could be fixed with enabling
whole compat package; let's see if that's the case
> Full compat

- .github/workflows/tag-client-pr.yml
- client/src/lib/utils/networkData.ts
- client/tests/paseo.test.ts
Resolves #437
This pull request includes an update to the `Paseo` network data in the `networkData.ts` file to add several new chains.
Changes to network data:
* [`client/src/lib/utils/networkData.ts`](diffhunk://#diff-18208224988b15c7ed0e5e9f908827fea45f65edd128b85a8e2453b84e11dac2L58-R64): Added new chains `AssetHub`, `BridgeHub`, `People`, and `Coretime` to the `Paseo` network.
> added support to `paseo` parachains ⛓️
